// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":true,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SAN_MapGenerator","status":true,"description":"自動マップ生成 ver1.11\r\n自動的にマップを生成しイベントを配置します。","parameters":{"WallHight":"1","MinRoomSize":"6","MaxRoomSize":"9","ShowOuterWall":"ON"}},
{"name":"EnemyManager","status":true,"description":"","parameters":{}},
{"name":"InfoWindow","status":true,"description":"","parameters":{}},
{"name":"TDDP_BindPicturesToMap","status":true,"description":"画像をマップに固定したり、レイヤーの変更をすることができます。","parameters":{}}
];
